# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10IRcMHsPKUlVa81Bw3vXrg-2WhbQTNfH
"""

!pip install -q streamlit

#Dependencies
import streamlit as st
import pickle
import pandas as pd

# Load the saved model
from google.colab import drive
drive.mount('/content/drive')

# Load the saved model
model_path = '/content/drive/My Drive/notebooks/final_model.pkl'

with open(model_path, 'rb') as model_file:
    loaded_model = pickle.load(model_file)

# Streamlit App
def main():
    st.title("Predicting Obesity Using Machine Learning Model")
    st.write("""This app allows you to predict an obesity diagnostic using a series of questions based on a dataset taken from Kaggle
    """)

    # Sidebar with user input
    st.sidebar.header("Questionnaire")

    #Defining options for checkboxes
    tf_options = ["True", "False"]
    frequency_options = ["Frequently", "Sometimes", "no"]
    transport_options = ["Bike", "Motobike", "Public Transportation", "Waking", "Automobile"]

    # Example input features (you can replace this with your actual input fields)
    age = st.sidebar.number_input("How old are you?", 0.0, 100.0, 50.0)
    height = st.sidebar.number_input("What is your height in meters?", 0.0, 2)
    weight = st.sidebar.number_input("What is your weight in kilograms?", 0.0, 200.0, 50.0)
    favc = st.sidebar.checkbox("Do you frequently consume high caloric foods? (Frequently meaning at least 2 servings a day)", frequency_options)
    fcvc = st.sidebar.select_slider("How frequently do you consume vegetables each day? (3 meaning at more than 2 servings a day, 2 meaning around 2 servings a day, 1 meaning one serving a day, 0 being none)", 0, 3, 2)
    ncp = st.sidebar.number_input("How many main meals do you generally have each day?", 0, 4, 2)
    caec = st.sidebar.checkbox("How often do you consume food in between meals?", frequency_options)
    ch20 = st.sidebar.checkbox("How often do you drink alcohol each day?", frequency_options)
    faf = st.sidebar.number_input("How frequently do you exercise each day?", 0, 3, 2)
    ch2o = st.sidebar.select_slider("How often do you drink water each day? (3 is frequently or about 6-8 cups a day, 2 is less frequently meaning 3-5 cups a day, 1 is 1-2 cups a day, and 0 is none)", 0, 3, 2)
    calc = st.sidebar.checkbox("Do you frequently consume alcohol?", frequency_options)
    smoke = st.sidebar.checkbox("Do you smoke?", tf_options)
    transportation = st.sidebar.checkbox("What mode of transportation do you generally take each day?", transport_options)


    # Perform actions based on the checkbox value
    ##FAVC
    if favc == 'Frequently':
        st.write("Feature 1 is selected.")
    else:
        st.write("Feature 1 is not selected.")
    ##CAEC
    ##CALC
    ##SMOKE
    ##TRANSPORTATION


    # Make predictions with the loaded model
    if st.form_submit_button("Predict"):
      data = pd.DataFrame({
        'Age': [age],
        'Height': [height],
        'Weight': [weight],
        'FCVC': [fcvc],
        'CH20': [ch20],
        'FAF': [faf],
        'FAVC_yes': [favc],
        "CAEC_Frequently": [caec],
        "CALC_Sometimes":  [caec],
        "CAEC_no": [caec],
        "SMOKE_yes":  [smoke],
        "CALC_Frequently":  [calc],
        "CALC_Sometimes":  [calc],
        "CALC_no":  [calc],
        "MTRANS_Bike":  [transportation],
        "MTRANS_Motorbike":  [transportation],
        "MTRANS_Public_Transportation":  [transportation],
        "MTRANS_Walking":  [transportation] })
      prediction = loaded_model.predict(data)
      # Display the prediction
      st.subheader("Prediction:")
      st.write(prediction)

   st.write("""Dataset from Kaggle: https://www.kaggle.com/datasets/aravindpcoder/obesity-or-cvd-risk-classifyregressorcluster
    """)


if __name__ == "__main__":
    main()

